services:
  fileman:
    build:
      context: .
      args:
        - "PUID=${PUID:-1000}"
        - "PGID=${PGID:-1000}"
    image: murilopereira.dev/fileman:latest
    container_name: fileman
    restart: unless-stopped
    environment:
      - CONFIG_PATH=config.json
    volumes:
      - /path/to/monitored/folder:/files
      - config.json:/app/config.json